repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint --rcfile=.pylintrc src/apologies tests
        pass_filenames: false
        language: system
