repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        args: [.]
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint --rcfile=.pylintrc src/apologies tests
        pass_filenames: false
        language: system
