# vim: set ft=yaml ts=2 sw=2 expandtab:
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-test:
    uses: ./.github/workflows/test-suite.yml
  release:
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-release.yml@master
    needs: [build-and-test]
    secrets: inherit
    with:
      python-version: "3.8"
      poetry-version: "1.3.1"
