name: Test Suite
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python }}
          poetry_version: 1.0.5
          args: install -v
      - name: Run Tox test suite
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python }}
          poetry_version: 1.0.5
          args: tox -c .toxrc -e "lint,{py37,py38}-{coverage,nocoverage}"
